apiVersion: v1
entries:
  camel-k:
  - apiVersion: v2
    appVersion: 1.8.2
    created: "2022-03-07T07:52:06.852933817+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: e36f0bf58c32e16fbf8ec87c44d990f7ba24a88d2b226c8470d53bbdf8297710
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    - email: acosentino@apache.org
      name: acosentino
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.9.2.tgz
    version: 0.9.2
  - apiVersion: v2
    appVersion: 1.8.1
    created: "2022-03-07T07:52:06.849594753+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 480c01430ab25a1a837c978a41d78b99065bcd316c1d37b895830f1b85c1b26e
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    - email: acosentino@apache.org
      name: acosentino
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2022-03-07T07:52:06.845831142+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: d087b2949da17ff24557bd57699751d3f9738a7be7c89d5172114136808424e1
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    - email: acosentino@apache.org
      name: acosentino
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2022-03-07T07:52:06.842460616+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: efccc4fab8d7f8b4e5ad129d9117e8a8d8fb5f65c7c3141eb07a63481eb7a4a7
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: 1.6.1
    created: "2022-03-07T07:52:06.838760547+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 949d4e2d12f3a7667ec5dcd924788ba38b955b75cdcf2b9c9fd8bda30d491b20
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.7.1.tgz
    version: 0.7.1
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2022-03-07T07:52:06.834828458+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 226251d742edff0f1a71d0068de67de348e0be0a8b29a411cad073ceb7d48535
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2022-03-07T07:52:06.831524569+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: a3f32e2e2d73361b9d4cda028c9c549ba5dfd5cbf1f0224a1badcff295292818
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2022-03-07T07:52:06.830549654+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: a011dd36bbfb07a23ca18baabec945274d2ac1164e08414147ecf683cccf8a21
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.3.2-SNAPSHOT
    created: "2022-03-07T07:52:06.829627314+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 30d999fb1a24c741829cd3ad1c1ba3c8ac4d0571a9ad1258c327c426913312d7
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2022-03-07T07:52:06.827271809+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 222b6b51ac7c836e1a7cfe44228de3666cb2b4c559c64bee35afaef9cbfe2449
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2022-03-07T07:52:06.825467009+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 393f4e4b32119824442ee2abdfc34a34bc49ec0fc6e957057e955cb5dd63aece
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2022-03-07T07:52:06.823753231+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: c47863e13644340b857acf5c688004927e0ad126a9c39e8c90fa6d84e2c445b9
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2022-03-07T07:52:06.821031839+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 46771bd1c0e52097f07e9c17e657690872716ed845b196cd0c981c97b984b573
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-03-07T07:52:06.818847094+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: d7453b9b6281355caad37896c6760be64735f69009bc312a54cbc17e8a1f6697
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-03-07T07:52:06.818233601+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 610a2b024d539451ee278b72179f34c242a67b7949e2a4eae7b0fa2d8d3630e3
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.0.0-RC2
    created: "2022-03-07T07:52:06.817746669+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 3d5397e111004a8735849dcebd55c9827e687aa3ab28b5c28de8fe69595e1b8f
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.0.0-RC2
    created: "2022-03-07T07:52:06.817241847+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 43fa5d9563ce76d25695e4132c5870279541b26be2ac8023537b587483853260
    home: https://camel.apache.org/camel-k/latest/
    icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0-RC2
    created: "2022-03-07T07:52:06.816767318+01:00"
    description: A lightweight integration platform, born on Kubernetes, with serverless
      superpowers
    digest: 3bc8c53c4d781c4b4e4aac254d291339b348c2d8b4cf24b579ceb4330a48edd5
    home: https://camel.apache.org/camel-k/latest/
    icon: https://raw.githubusercontent.com/apache/camel/master/docs/img/logo-d.svg
    keywords:
    - serverless
    - integration
    - patterns
    maintainers:
    - email: nferraro@apache.org
      name: nferraro
    name: camel-k
    sources:
    - https://github.com/apache/camel-k
    - https://github.com/apache/camel-k-runtime
    - https://github.com/apache/camel-quarkus
    - https://github.com/apache/camel
    type: application
    urls:
    - https://apache.github.io/camel-k/charts/camel-k-0.1.0.tgz
    version: 0.1.0
generated: "2022-03-07T07:52:06.816108619+01:00"
